apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: test-rel-arttekdot 
  janus-idp.io/tekton: test-rel-arttekdot
  backstage.io/kubernetes-id: test-rel-arttekdot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: test-rel-arttekdot
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  